var Translate={
	title:"Digital Video Recorder",
	usr:"Username:",
	pswd:"Password:",
	logi:"please login in!",
	login:"Login",
	dev:"device",
	ch:"CAM ",
	MFt:"MainStream",
	SFt:"SubStream",
	Zoom:"zoom",
	Iris:"Iris",
	Focu:"focus",
	Split1:"View 1",
	Split4:"View 4",
	Split9:"View 9",
	Split16:"View 16",
	Split25:"View 25",
	Split36:"View 36",
	PlayAll:"connect all video",
	StopPlayAll:"close all video",
	mainPlayAll:"playAll(mainStream)",
	subPlayAll:"playAll(subStream)",
	ok:"ok",
	Cancel:"Cancel",
	logout:"Logout",
	autoPrompt:"Auto Prompt",
	version:"Version",
	NeedOCX:"Need ActiveX...",
	Reason:"Need install some ActiveX controls to view the real time video.",
	Step1:"Step 1:",
	Situation1:" If there is a message at the top of this page，please click this message and select ",
	InstallActiveX:"'Install ActiveX control...'",
	Step2:" Step 2:",
	Situation2:" After this window appeared，please click the button ",
	Install:"'Install'",
	If1:"If this message dosn't appeare ...",
	click:"Click the button ",
	refresh:"Refresh",
	check:" to refresh this page and check if the message appeare.",
	If2:"If the message dosn't appeare yet，pleace click the button ",
	Download:"Download software",
	Mannual:" to download the ActiveX control setup software to install it by manual."
}

var Versions=
{   
    vidioIn:"Vidio In: ",
    audioIn:"Audio In: ",
    alarmIn:"Alarm In: ",
    alarmOut:"Alarm Output: ",
    buildTime:"Build Date:",
    version:"System: ",
    serialNo:"Serial ID: " ,
    ok:"ok" 
    
}
